name: Lighthouse Performance Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    name: Run Lighthouse
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Lighthouse
      run: npm install -g @lhci/cli@0.12.x
    
    - name: Run Lighthouse
      run: |
        lhci autorun --collect.staticDistDir=. --collect.url=index.html || echo "Lighthouse completed with warnings"
    
    - name: Upload Lighthouse Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results
        path: .lighthouseci/